trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

  # Pipeline configuration (Disable shallow fetch).
  # See https://dev.to/kkazala/azure-devops-pipelines-shallow-fetch-1-is-now-default-4656 for more details.
  # See https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch for more details.
  Agent.Source.Git.ShallowFetchDepth: 0

steps:
- task: gitversion/setup@0
  inputs:
    versionSpec: '5.12.0'
  displayName: 'Install GitVersion'

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml
  displayName: 'Calculate Version'

- script: dotnet build --configuration $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersionV2) -p:FileVersion=$(GitVersion.AssemblySemVer) -p:InformationalVersion=$(GitVersion.InformationalVersion)
  displayName: Build

- script: dotnet test --no-build --configuration $(buildConfiguration) --logger:trx
  displayName: Test

- task: PublishTestResults@2
  displayName: Publish Tests Results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    testRunTitle: 'Unit Tests'

- script: dotnet pack --no-build --configuration $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersionV2) --output $(build.artifactStagingDirectory)
  displayName: Pack

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'

- task: NuGetToolInstaller@1
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('true', variables['forcePushNuget'])))
  inputs:
    versionSpec: '>= 4.9'
    checkLatest: true

- task: NuGetCommand@2
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('true', variables['forcePushNuget'])))
  inputs:
    command: 'push'
    packagesToPush: '$(build.artifactStagingDirectory)/**/*.nupkg;!$(build.artifactStagingDirectory)/**/*.snupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org - nventive'
